import { Category, IngredientRef, Venue } from '@/types'

export const mockVenue: Venue = {
  id: '1',
  name: 'Кофейня «Утро»',
  slug: 'utro',
  address: 'ул. Пушкина, 12',
  description: 'Уютная кофейня с авторскими завтраками',
  workingHours: 'до 22:00',
  tags: ['Кофе', 'Завтраки', 'Веган'],
}

// Переиспользуемые группы молока
const milkModifierGroup = {
  id: 'milk',
  label: 'Молоко',
  multi: false,
  required: true,
  modifiers: [
    { id: 'milk-classic', label: 'Классическое', calories: 0, protein: 0, fat: 0, carbs: 0, weight: 0, weightUnit: 'мл' as const },
    { id: 'milk-coconut', label: 'Кокосовое Planto', calories: 31, protein: 0.9, fat: 1.3, carbs: 3.8, weight: 100, weightUnit: 'мл' as const },
    { id: 'milk-banana', label: 'Банановое Planto', calories: 44, protein: 1.2, fat: 0.7, carbs: 8.3, weight: 100, weightUnit: 'мл' as const },
    { id: 'milk-almond', label: 'Миндальное Planto', calories: 24, protein: 0.4, fat: 1.2, carbs: 2.9, weight: 100, weightUnit: 'мл' as const },
    { id: 'milk-hazelnut', label: 'Фундучное Гринмилк', calories: 45, protein: 1, fat: 2, carbs: 5.5, weight: 100, weightUnit: 'мл' as const },
    { id: 'milk-lactose', label: 'Безлактозное Parmalat', calories: 47, protein: 3, fat: 1.8, carbs: 4.7, weight: 100, weightUnit: 'мл' as const },
  ],
}

const additivesGroup = {
  id: 'additives',
  label: 'Добавки',
  multi: true,
  required: false,
  modifiers: [
    { id: 'add-sugar', label: 'Сахар', calories: 20, protein: 0, fat: 0, carbs: 5, weight: 5, weightUnit: 'г' as const },
    { id: 'add-vanilla', label: 'Ванильный сахар', calories: 20, protein: 0, fat: 0, carbs: 5, weight: 5, weightUnit: 'г' as const },
    { id: 'add-cinnamon', label: 'Корица', calories: 6, protein: 0.1, fat: 0.1, carbs: 2, weight: 2, weightUnit: 'г' as const },
    { id: 'add-peanut', label: 'Арахис дроблёный', calories: 56, protein: 2.6, fat: 4.8, carbs: 1.4, weight: 10, weightUnit: 'г' as const },
    { id: 'add-marsh', label: 'Маршмеллоу', calories: 32, protein: 0.5, fat: 0, carbs: 7.7, weight: 10, weightUnit: 'г' as const },
  ],
}

// Сироп с зависимостью от объёма — добавляем отдельно в каждый напиток

export const mockCategories: Category[] = [
  {
    id: 'drinks-classic',
    name: 'Кофе — классика',
    venueId: '1',
    order: 1,
    items: [
      {
        id: 'espresso',
        name: 'Эспрессо',
        description: 'Классический эспрессо',
        weight: 30, weightUnit: 'мл',
        calories: 2, protein: 0.1, fat: 0, carbs: 0.1,
        categoryId: 'drinks-classic', venueId: '1', isAvailable: true,
        modifierGroups: [additivesGroup],
      },
      {
        id: 'americano',
        name: 'Американо',
        description: 'Эспрессо с горячей водой',
        weight: 200, weightUnit: 'мл',
        calories: 2, protein: 0.2, fat: 0.1, carbs: 0,
        categoryId: 'drinks-classic', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'volume',
            label: 'Объём',
            required: true,
            options: [
              { id: 'v-02', label: '0.2', calories: 2, protein: 0.2, fat: 0.1, carbs: 0, weight: 200, weightUnit: 'мл' },
              { id: 'v-03', label: '0.3', calories: 3, protein: 0.1, fat: 0.1, carbs: 0, weight: 300, weightUnit: 'мл' },
            ],
          },
        ],
        modifierGroups: [
          additivesGroup,
          {
            id: 'syrup',
            label: 'Сироп',
            multi: false,
            required: false,
            modifiers: [
              { id: 'syrup-none', label: 'Без сиропа', calories: 0, protein: 0, fat: 0, carbs: 0, weight: 0, weightUnit: 'мл' },
              { id: 'syrup-15', label: 'Сироп 15 мл', calories: 45, protein: 0, fat: 0, carbs: 11, weight: 15, weightUnit: 'мл' },
              { id: 'syrup-20', label: 'Сироп 20 мл', calories: 60, protein: 0, fat: 0, carbs: 15, weight: 20, weightUnit: 'мл' },
              { id: 'syrup-25', label: 'Сироп 25 мл', calories: 75, protein: 0, fat: 0, carbs: 19, weight: 25, weightUnit: 'мл' },
            ],
          },
          {
            id: 'milk-add',
            label: 'Молоко +50 мл',
            multi: false,
            required: false,
            modifiers: [
              { id: 'milk-add-no', label: 'Без молока', calories: 0, protein: 0, fat: 0, carbs: 0, weight: 0, weightUnit: 'мл' },
              { id: 'milk-add-classic', label: 'Классическое', calories: 30, protein: 1.5, fat: 1.8, carbs: 2.4, weight: 50, weightUnit: 'мл' },
              { id: 'milk-add-coconut', label: 'Кокосовое Planto', calories: 16, protein: 0.5, fat: 0.7, carbs: 1.9, weight: 50, weightUnit: 'мл' },
              { id: 'milk-add-banana', label: 'Банановое Planto', calories: 22, protein: 0.6, fat: 0.4, carbs: 4.2, weight: 50, weightUnit: 'мл' },
              { id: 'milk-add-almond', label: 'Миндальное Planto', calories: 12, protein: 0.2, fat: 0.6, carbs: 1.5, weight: 50, weightUnit: 'мл' },
              { id: 'milk-add-hazelnut', label: 'Фундучное Гринмилк', calories: 23, protein: 0.5, fat: 1, carbs: 2.8, weight: 50, weightUnit: 'мл' },
              { id: 'milk-add-lactose', label: 'Безлактозное Parmalat', calories: 24, protein: 1.5, fat: 0.9, carbs: 2.4, weight: 50, weightUnit: 'мл' },
            ],
          },
        ],
      },
      {
        id: 'flat-white',
        name: 'Флэт уайт',
        description: 'Двойной эспрессо с молоком',
        weight: 160, weightUnit: 'мл',
        calories: 97, protein: 4.7, fat: 5.1, carbs: 7.6,
        categoryId: 'drinks-classic', venueId: '1', isAvailable: true,
        modifierGroups: [milkModifierGroup, additivesGroup],
      },
      {
        id: 'cappuccino',
        name: 'Капучино',
        description: 'Эспрессо, молочная пена',
        weight: 250, weightUnit: 'мл',
        calories: 108, protein: 5.2, fat: 5.8, carbs: 8.5,
        categoryId: 'drinks-classic', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'volume',
            label: 'Объём',
            required: true,
            options: [
              { id: 'v-025', label: '0.25', calories: 108, protein: 5.2, fat: 5.8, carbs: 8.5, weight: 250, weightUnit: 'мл' },
              { id: 'v-03', label: '0.3', calories: 168, protein: 8.2, fat: 9.0, carbs: 13.3, weight: 300, weightUnit: 'мл' },
            ],
          },
        ],
        modifierGroups: [milkModifierGroup, additivesGroup],
      },
      {
        id: 'latte',
        name: 'Латте',
        description: 'Эспрессо, молоко',
        weight: 300, weightUnit: 'мл',
        calories: 173, protein: 8.4, fat: 9.3, carbs: 13.6,
        categoryId: 'drinks-classic', venueId: '1', isAvailable: true,
        modifierGroups: [milkModifierGroup, additivesGroup],
      },
      {
        id: 'mocco',
        name: 'Мокко',
        description: 'Эспрессо, шоколад, молоко',
        weight: 300, weightUnit: 'мл',
        calories: 228, protein: 8.3, fat: 12.9, carbs: 19.0,
        categoryId: 'drinks-classic', venueId: '1', isAvailable: true,
        modifierGroups: [milkModifierGroup, additivesGroup],
      },
      {
        id: 'raf',
        name: 'Раф',
        description: 'Эспрессо, сливки, ваниль',
        weight: 300, weightUnit: 'мл',
        calories: 315, protein: 8.8, fat: 19.8, carbs: 24.8,
        categoryId: 'drinks-classic', venueId: '1', isAvailable: true,
        modifierGroups: [additivesGroup],
      },
      {
        id: 'matcha-latte',
        name: 'Матча-латте',
        description: 'Японский матча, молоко',
        weight: 250, weightUnit: 'мл',
        calories: 112, protein: 5.8, fat: 6.0, carbs: 8.6,
        categoryId: 'drinks-classic', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'volume',
            label: 'Объём',
            required: true,
            options: [
              { id: 'v-025', label: '0.25', calories: 112, protein: 5.8, fat: 6.0, carbs: 8.6, weight: 250, weightUnit: 'мл' },
              { id: 'v-03', label: '0.3', calories: 167, protein: 8.8, fat: 8.9, carbs: 12.9, weight: 300, weightUnit: 'мл' },
            ],
          },
        ],
        modifierGroups: [milkModifierGroup, additivesGroup],
      },
      {
        id: 'cocoa',
        name: 'Какао',
        description: 'Натуральное какао',
        weight: 200, weightUnit: 'мл',
        calories: 137, protein: 7.1, fat: 7.2, carbs: 11.1,
        categoryId: 'drinks-classic', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'volume',
            label: 'Объём',
            required: true,
            options: [
              { id: 'v-02', label: '0.2', calories: 137, protein: 7.1, fat: 7.2, carbs: 11.1, weight: 200, weightUnit: 'мл' },
              { id: 'v-03', label: '0.3', calories: 205, protein: 10.7, fat: 10.7, carbs: 16.5, weight: 300, weightUnit: 'мл' },
            ],
          },
        ],
        modifierGroups: [milkModifierGroup, additivesGroup],
      },
      {
        id: 'orange-fresh',
        name: 'Апельсиновый фреш',
        description: 'Свежевыжатый апельсин',
        weight: 200, weightUnit: 'мл',
        calories: 90, protein: 2.3, fat: 0.5, carbs: 20.3,
        categoryId: 'drinks-classic', venueId: '1', isAvailable: true,
      },
    ],
  },
  {
    id: 'drinks-author',
    name: 'Авторские напитки',
    venueId: '1',
    order: 2,
    items: [
      {
        id: 'peanut-raf',
        name: 'Арахисовый раф',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 352, protein: 13.4, fat: 20.5, carbs: 28.2,
        categoryId: 'drinks-author', venueId: '1', isAvailable: true,
        modifierGroups: [milkModifierGroup],
      },
      {
        id: 'latte-mint',
        name: 'Латте мята-лайм-гибискус',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 199, protein: 8, fat: 4, carbs: 23.2,
        categoryId: 'drinks-author', venueId: '1', isAvailable: true,
        modifierGroups: [milkModifierGroup],
      },
      {
        id: 'latte-pear',
        name: 'Латте груша-карамель',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 165, protein: 4.5, fat: 4.8, carbs: 26.9,
        categoryId: 'drinks-author', venueId: '1', isAvailable: true,
        modifierGroups: [milkModifierGroup],
      },
      {
        id: 'latte-raspberry',
        name: 'Латте малина-фиалка',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 256, protein: 7.8, fat: 8.3, carbs: 38.8,
        categoryId: 'drinks-author', venueId: '1', isAvailable: true,
        modifierGroups: [milkModifierGroup],
      },
      {
        id: 'plum-glintv',
        name: 'Сливовый глинтвейн',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 91, protein: 0.3, fat: 0, carbs: 22,
        categoryId: 'drinks-author', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'volume',
            label: 'Объём',
            required: true,
            options: [
              { id: 'v-03', label: '0.3', calories: 91, protein: 0.3, fat: 0, carbs: 22, weight: 300, weightUnit: 'мл' },
              { id: 'v-04', label: '0.4', calories: 114, protein: 0.4, fat: 0, carbs: 27.8, weight: 400, weightUnit: 'мл' },
            ],
          },
        ],
      },
      {
        id: 'mango-shake',
        name: 'Манговый милкшейк',
        description: '',
        weight: 400, weightUnit: 'мл',
        calories: 469, protein: 10.8, fat: 20.4, carbs: 61.4,
        categoryId: 'drinks-author', venueId: '1', isAvailable: true,
      },
      {
        id: 'smoothie-pine',
        name: 'Смузи ананас-мята',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 258, protein: 2.8, fat: 0.3, carbs: 64.2,
        categoryId: 'drinks-author', venueId: '1', isAvailable: true,
      },
      {
        id: 'smoothie-spinach',
        name: 'Смузи шпинат-финик',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 241, protein: 4.5, fat: 0.5, carbs: 59.7,
        categoryId: 'drinks-author', venueId: '1', isAvailable: true,
      },
      {
        id: 'smoothie-protein',
        name: 'Протеиновый смузи лесные ягоды',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 391, protein: 26.8, fat: 6, carbs: 13,
        categoryId: 'drinks-author', venueId: '1', isAvailable: true,
      },
    ],
  },
  {
    id: 'drinks-tea',
    name: 'Чай и холодные',
    venueId: '1',
    order: 3,
    items: [
      {
        id: 'tea-sea',
        name: 'Облепиховый чай',
        description: '',
        weight: 500, weightUnit: 'мл',
        calories: 174, protein: 1.5, fat: 4.3, carbs: 31.8,
        categoryId: 'drinks-tea', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'format',
            label: 'Формат',
            required: true,
            options: [
              { id: 'teapot', label: 'Чайник', calories: 174, protein: 1.5, fat: 4.3, carbs: 31.8, weight: 500, weightUnit: 'мл' },
              { id: 'togo', label: 'To go', calories: 127, protein: 1, fat: 3.2, carbs: 23.4, weight: 350, weightUnit: 'мл' },
            ],
          },
        ],
      },
      {
        id: 'tea-lemon',
        name: 'Лимонно-имбирный чай',
        description: '',
        weight: 500, weightUnit: 'мл',
        calories: 190, protein: 0.7, fat: 0, carbs: 43.7,
        categoryId: 'drinks-tea', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'format',
            label: 'Формат',
            required: true,
            options: [
              { id: 'teapot', label: 'Чайник', calories: 190, protein: 0.7, fat: 0, carbs: 43.7, weight: 500, weightUnit: 'мл' },
              { id: 'togo', label: 'To go', calories: 157, protein: 0.4, fat: 0, carbs: 36.7, weight: 350, weightUnit: 'мл' },
            ],
          },
        ],
      },
      {
        id: 'tea-rose',
        name: 'Роза-клубника',
        description: '',
        weight: 500, weightUnit: 'мл',
        calories: 234, protein: 0.9, fat: 0.2, carbs: 56.4,
        categoryId: 'drinks-tea', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'format',
            label: 'Формат',
            required: true,
            options: [
              { id: 'teapot', label: 'Чайник', calories: 234, protein: 0.9, fat: 0.2, carbs: 56.4, weight: 500, weightUnit: 'мл' },
              { id: 'togo', label: 'To go', calories: 162, protein: 0.5, fat: 0.1, carbs: 39.1, weight: 350, weightUnit: 'мл' },
            ],
          },
        ],
      },
      {
        id: 'tea-cherry',
        name: 'Вишня-бергамот',
        description: '',
        weight: 500, weightUnit: 'мл',
        calories: 173, protein: 0.8, fat: 0.2, carbs: 40.3,
        categoryId: 'drinks-tea', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'format',
            label: 'Формат',
            required: true,
            options: [
              { id: 'teapot', label: 'Чайник', calories: 173, protein: 0.8, fat: 0.2, carbs: 40.3, weight: 500, weightUnit: 'мл' },
              { id: 'togo', label: 'To go', calories: 135, protein: 0.6, fat: 0.2, carbs: 32.2, weight: 350, weightUnit: 'мл' },
            ],
          },
        ],
      },
      {
        id: 'ice-latte',
        name: 'Айс-латте с сиропом',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 196, protein: 7.2, fat: 7.7, carbs: 24.3,
        categoryId: 'drinks-tea', venueId: '1', isAvailable: true,
        modifierGroups: [milkModifierGroup],
      },
      {
        id: 'espresso-tonic',
        name: 'Эспрессо-тоник',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 43, protein: 0, fat: 0, carbs: 10.6,
        categoryId: 'drinks-tea', venueId: '1', isAvailable: true,
      },
      {
        id: 'bumble',
        name: 'Бамбл',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 153, protein: 0, fat: 0, carbs: 38.2,
        categoryId: 'drinks-tea', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'syrup',
            label: 'Сироп',
            required: true,
            options: [
              { id: 'with-syrup', label: 'С сиропом', calories: 153, protein: 0, fat: 0, carbs: 38.2, weight: 300, weightUnit: 'мл' },
              { id: 'no-syrup', label: 'Без сиропа', calories: 101, protein: 0, fat: 0, carbs: 25.2, weight: 300, weightUnit: 'мл' },
            ],
          },
        ],
      },
      {
        id: 'ice-matcha',
        name: 'Айс-матча латте',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 144, protein: 7.2, fat: 7.7, carbs: 11.3,
        categoryId: 'drinks-tea', venueId: '1', isAvailable: true,
        modifierGroups: [milkModifierGroup],
      },
      {
        id: 'ice-matcha-tonic',
        name: 'Айс-матча тоник',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 43, protein: 0, fat: 0, carbs: 10.6,
        categoryId: 'drinks-tea', venueId: '1', isAvailable: true,
      },
      {
        id: 'ice-rooibos',
        name: 'Айс ти сливочный ройбуш',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 196, protein: 7.2, fat: 7.7, carbs: 24.3,
        categoryId: 'drinks-tea', venueId: '1', isAvailable: true,
      },
    ],
  },

  // ─── ЕДА ───────────────────────────────────────────────────
  {
    id: 'food-tortilla',
    name: 'Тортилья',
    venueId: '1',
    order: 4,
    items: [
      {
        id: 'tortilla',
        name: 'Тортилья',
        description: 'Пшеничная лепёшка с начинкой на выбор',
        weight: 300, weightUnit: 'г',
        calories: 326, protein: 10, fat: 16, carbs: 37,
        categoryId: 'food-tortilla', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'filling',
            label: 'Начинка',
            required: true,
            options: [
              { id: 'veg', label: 'С овощами', calories: 326, protein: 10, fat: 16, carbs: 37, weight: 300, weightUnit: 'г' },
              { id: 'chicken', label: 'С курицей', calories: 357, protein: 18, fat: 16, carbs: 35, weight: 300, weightUnit: 'г' },
              { id: 'salmon', label: 'С лососем', calories: 391, protein: 16, fat: 20, carbs: 37, weight: 300, weightUnit: 'г' },
              { id: 'shrimp', label: 'С креветкой', calories: 335, protein: 18, fat: 12, carbs: 38, weight: 300, weightUnit: 'г' },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'food-bowl',
    name: 'Боул',
    venueId: '1',
    order: 5,
    items: [
      {
        id: 'bowl',
        name: 'Боул',
        description: 'Питательный боул с крупой и начинкой на выбор',
        weight: 400, weightUnit: 'г',
        calories: 220, protein: 8, fat: 9.5, carbs: 23,
        categoryId: 'food-bowl', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'filling',
            label: 'Начинка',
            required: true,
            options: [
              { id: 'veg', label: 'Вегетарианский', calories: 0, protein: 0, fat: 0, carbs: 0, weight: 0, weightUnit: 'г' },
              { id: 'chicken', label: 'С курицей', calories: 0, protein: 0, fat: 0, carbs: 0, weight: 0, weightUnit: 'г' },
              { id: 'salmon', label: 'С лососем', calories: 0, protein: 0, fat: 0, carbs: 0, weight: 0, weightUnit: 'г' },
              { id: 'shrimp', label: 'С креветкой', calories: 0, protein: 0, fat: 0, carbs: 0, weight: 0, weightUnit: 'г' },
              { id: 'tuna', label: 'С тунцом', calories: 0, protein: 0, fat: 0, carbs: 0, weight: 0, weightUnit: 'г' },
            ],
          },
          {
            id: 'grain',
            label: 'Крупа',
            required: true,
            options: [
              { id: 'bulgur', label: 'Булгур', calories: 0, protein: 0, fat: 0, carbs: 0, weight: 0, weightUnit: 'г' },
              { id: 'quinoa', label: 'Киноа', calories: 0, protein: 0, fat: 0, carbs: 0, weight: 0, weightUnit: 'г' },
              { id: 'buckwheat', label: 'Гречка', calories: 0, protein: 0, fat: 0, carbs: 0, weight: 0, weightUnit: 'г' },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'food-main',
    name: 'Основные блюда',
    venueId: '1',
    order: 6,
    items: [
      { id: 'pasta', name: 'Паста карбонара', description: '', weight: 350, weightUnit: 'г', calories: 760, protein: 47.9, fat: 30.6, carbs: 70.4, categoryId: 'food-main', venueId: '1', isAvailable: true },
      { id: 'burger-doctor', name: 'Бургер с докторской и омлетом', description: '', weight: 350, weightUnit: 'г', calories: 646, protein: 23.6, fat: 45.9, carbs: 35.4, categoryId: 'food-main', venueId: '1', isAvailable: true },
      { id: 'burger-shrimp', name: 'Бургер с креветкой и авокадо', description: '', weight: 320, weightUnit: 'г', calories: 525, protein: 19.3, fat: 32.7, carbs: 40.2, categoryId: 'food-main', venueId: '1', isAvailable: true },
      { id: 'shakshuka', name: 'Шакшука', description: '', weight: 300, weightUnit: 'г', calories: 306, protein: 18.6, fat: 24.3, carbs: 31, categoryId: 'food-main', venueId: '1', isAvailable: true },
      { id: 'buckwheat-turkey', name: 'Греча с индейкой и яйцом пашот', description: '', weight: 400, weightUnit: 'г', calories: 581, protein: 46, fat: 24.7, carbs: 49, categoryId: 'food-main', venueId: '1', isAvailable: true },
    ],
  },
  {
    id: 'food-breakfast',
    name: 'Завтраки',
    venueId: '1',
    order: 7,
    items: [
      { id: 'avocado-toast', name: 'Авокадо тост', description: '', weight: 250, weightUnit: 'г', calories: 466, protein: 18.8, fat: 33.2, carbs: 24.3, categoryId: 'food-breakfast', venueId: '1', isAvailable: true },
      {
        id: 'croissant',
        name: 'Круассан',
        description: '',
        weight: 200, weightUnit: 'г',
        calories: 479, protein: 13, fat: 29, carbs: 44,
        categoryId: 'food-breakfast', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'filling',
            label: 'Начинка',
            required: true,
            options: [
              { id: 'salmon', label: 'С лососем', calories: 479, protein: 13, fat: 29, carbs: 44, weight: 200, weightUnit: 'г' },
              { id: 'brie', label: 'С бри и вишней', calories: 457, protein: 13, fat: 28, carbs: 37, weight: 200, weightUnit: 'г' },
            ],
          },
        ],
      },
      {
        id: 'brioche',
        name: 'Бриошь',
        description: '',
        weight: 150, weightUnit: 'г',
        calories: 345, protein: 9.7, fat: 26.7, carbs: 17.4,
        categoryId: 'food-breakfast', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'filling',
            label: 'Начинка',
            required: true,
            options: [
              { id: 'butter-caviar', label: 'С маслом и икрой', calories: 345, protein: 9.7, fat: 26.7, carbs: 17.4, weight: 150, weightUnit: 'г' },
              { id: 'berries', label: 'С ягодами', calories: 642, protein: 12, fat: 30, carbs: 84, weight: 200, weightUnit: 'г' },
            ],
          },
        ],
      },
      {
        id: 'waffle',
        name: 'Вафля сырная',
        description: '',
        weight: 300, weightUnit: 'г',
        calories: 652, protein: 32, fat: 37, carbs: 48,
        categoryId: 'food-breakfast', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'filling',
            label: 'Начинка',
            required: true,
            options: [
              { id: 'salmon', label: 'С лососем', calories: 652, protein: 32, fat: 37, carbs: 48, weight: 300, weightUnit: 'г' },
              { id: 'avocado', label: 'С авокадо и икрой', calories: 466, protein: 22.6, fat: 32.6, carbs: 21.4, weight: 280, weightUnit: 'г' },
              { id: 'plain', label: 'Без начинки', calories: 187, protein: 7.5, fat: 9.9, carbs: 16.9, weight: 100, weightUnit: 'г' },
            ],
          },
        ],
      },
      { id: 'syrnik', name: 'Сырник со сметаной, черникой и маком', description: '', weight: 300, weightUnit: 'г', calories: 616, protein: 24.1, fat: 38.5, carbs: 40.4, categoryId: 'food-breakfast', venueId: '1', isAvailable: true },
    ],
  },
  {
    id: 'food-kids',
    name: 'Детское меню',
    venueId: '1',
    order: 8,
    items: [
      { id: 'kids-turkey', name: 'Индейка с овощами', description: '', weight: 250, weightUnit: 'г', calories: 183, protein: 33, fat: 3, carbs: 18.7, categoryId: 'food-kids', venueId: '1', isAvailable: true },
      { id: 'kids-soup', name: 'Суп с фрикадельками', description: '', weight: 300, weightUnit: 'г', calories: 176, protein: 10.9, fat: 5.7, carbs: 20.6, categoryId: 'food-kids', venueId: '1', isAvailable: true },
      { id: 'kids-patty', name: 'Биточки из индейки с пюре', description: '', weight: 300, weightUnit: 'г', calories: 593, protein: 25, fat: 41, carbs: 29.7, categoryId: 'food-kids', venueId: '1', isAvailable: true },
      { id: 'kids-pasta', name: 'Макарошки с сыром', description: '', weight: 250, weightUnit: 'г', calories: 328, protein: 14, fat: 18.9, carbs: 24.8, categoryId: 'food-kids', venueId: '1', isAvailable: true },
    ],
  },
  {
    id: 'sweets',
    name: 'Десерты',
    venueId: '1',
    order: 9,
    items: [
      { id: 'tart-flower', name: 'Тарт цветок', description: '', weight: 120, weightUnit: 'г', calories: 496, protein: 6.2, fat: 32.7, carbs: 44.8, categoryId: 'sweets', venueId: '1', isAvailable: true },
      { id: 'tiramisu', name: 'Тирамису', description: '', weight: 130, weightUnit: 'г', calories: 345, protein: 7.3, fat: 26, carbs: 19.3, categoryId: 'sweets', venueId: '1', isAvailable: true },
      { id: 'cheesecake', name: 'Чизкейк', description: '', weight: 130, weightUnit: 'г', calories: 522, protein: 8.8, fat: 38.6, carbs: 34.5, categoryId: 'sweets', venueId: '1', isAvailable: true },
      { id: 'medovik', name: 'Медовик', description: '', weight: 120, weightUnit: 'г', calories: 387, protein: 6.4, fat: 11.3, carbs: 64.7, categoryId: 'sweets', venueId: '1', isAvailable: true },
      { id: 'brownie', name: 'Брауни картошка', description: '', weight: 80, weightUnit: 'г', calories: 208, protein: 2.3, fat: 14.2, carbs: 18, categoryId: 'sweets', venueId: '1', isAvailable: true },
      { id: 'macaron-van', name: 'Макарун ванильный', description: '', weight: 30, weightUnit: 'г', calories: 328, protein: 6.6, fat: 15.9, carbs: 41.4, categoryId: 'sweets', venueId: '1', isAvailable: true },
      { id: 'macaron-choc', name: 'Макарун шоколадный', description: '', weight: 30, weightUnit: 'г', calories: 315, protein: 6.6, fat: 15.4, carbs: 39, categoryId: 'sweets', venueId: '1', isAvailable: true },
      { id: 'croissant-choc', name: 'Круассан шоколадный', description: 'Delifrance', weight: 80, weightUnit: 'г', calories: 246, protein: 5.4, fat: 2.7, carbs: 33.2, categoryId: 'sweets', venueId: '1', isAvailable: true },
      { id: 'eclair', name: 'Эклер', description: 'Ромбуле', weight: 80, weightUnit: 'г', calories: 278, protein: 4, fat: 14, carbs: 33, categoryId: 'sweets', venueId: '1', isAvailable: true },
    ],
  },
]

export const mockIngredients: IngredientRef[] = [
  {
    id: 'ing-buckwheat-cooked',
    name: 'Гречка варёная',
    unit: 'г',
    caloriesPer100: 110,
    proteinPer100: 4.2,
    fatPer100: 1.1,
    carbsPer100: 21.3,
    category: 'Крупа',
  },
]