import { Category, IngredientLibrary, IngredientRef, Venue } from '@/types'
import { systemIngredients } from '@/lib/data/systemIngredients'
import { foodDatabaseLibrary } from '@/lib/data/foodDatabase'

export const mockVenue: Venue = {
  id: '1',
  name: 'Кофейня «Утро»',
  slug: 'utro',
  address: 'ул. Пушкина, 12',
  description: 'Уютная кофейня с авторскими завтраками',
  workingHours: 'до 22:00',
  tags: ['Кофе', 'Завтраки', 'Веган'],
}

// Переиспользуемые группы молока
// Значения — абсолютный вклад порции молока (~150 мл) в КБЖУ напитка.
// Расчёт замены: Δ = выбранное − классическое (первое в списке).
const milkModifierGroup = {
  id: 'milk',
  label: 'Молоко',
  multi: false,
  required: true,
  modifiers: [
    { id: 'milk-classic',  label: 'Классическое',          calories: 90, protein: 4.5, fat: 4.8, carbs: 7.0, weight: 150, weightUnit: 'мл' as const },
    { id: 'milk-coconut',  label: 'Кокосовое Planto',       calories: 47, protein: 1.4, fat: 2.0, carbs: 5.7, weight: 150, weightUnit: 'мл' as const },
    { id: 'milk-banana',   label: 'Банановое Planto',        calories: 66, protein: 1.8, fat: 1.1, carbs: 12.5, weight: 150, weightUnit: 'мл' as const },
    { id: 'milk-almond',   label: 'Миндальное Planto',       calories: 36, protein: 0.6, fat: 1.8, carbs: 4.4, weight: 150, weightUnit: 'мл' as const },
    { id: 'milk-hazelnut', label: 'Фундучное Гринмилк',      calories: 68, protein: 1.5, fat: 3.0, carbs: 8.3, weight: 150, weightUnit: 'мл' as const },
    { id: 'milk-lactose',  label: 'Безлактозное Parmalat',   calories: 71, protein: 4.5, fat: 2.7, carbs: 7.1, weight: 150, weightUnit: 'мл' as const },
  ],
}

const additivesGroup = {
  id: 'additives',
  label: 'Добавки',
  multi: true,
  required: false,
  modifiers: [
    { id: 'add-sugar', label: 'Сахар', calories: 20, protein: 0, fat: 0, carbs: 5, weight: 5, weightUnit: 'г' as const },
    { id: 'add-vanilla', label: 'Ванильный сахар', calories: 20, protein: 0, fat: 0, carbs: 5, weight: 5, weightUnit: 'г' as const },
    { id: 'add-cinnamon', label: 'Корица', calories: 6, protein: 0.1, fat: 0.1, carbs: 2, weight: 2, weightUnit: 'г' as const },
    { id: 'add-peanut', label: 'Арахис дроблёный', calories: 56, protein: 2.6, fat: 4.8, carbs: 1.4, weight: 10, weightUnit: 'г' as const },
    { id: 'add-marsh', label: 'Маршмеллоу', calories: 32, protein: 0.5, fat: 0, carbs: 7.7, weight: 10, weightUnit: 'г' as const },
  ],
}

// Сироп с зависимостью от объёма — добавляем отдельно в каждый напиток

export const mockCategories: Category[] = [
  {
    id: 'drinks-classic',
    name: 'Кофе — классика',
    venueId: '1',
    order: 1,
    items: [
      {
        id: 'espresso',
        name: 'Эспрессо',
        description: 'Классический эспрессо',
        weight: 30, weightUnit: 'мл',
        calories: 2, protein: 0.1, fat: 0, carbs: 0.1,
        categoryId: 'drinks-classic', venueId: '1', isAvailable: true,
        modifierGroups: [additivesGroup],
      },
      {
        id: 'americano',
        name: 'Американо',
        description: 'Эспрессо с горячей водой',
        weight: 200, weightUnit: 'мл',
        calories: 2, protein: 0.2, fat: 0.1, carbs: 0,
        categoryId: 'drinks-classic', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'volume',
            label: 'Объём',
            required: true,
            options: [
              { id: 'v-02', label: '0.2', calories: 2, protein: 0.2, fat: 0.1, carbs: 0, weight: 200, weightUnit: 'мл' },
              { id: 'v-03', label: '0.3', calories: 3, protein: 0.1, fat: 0.1, carbs: 0, weight: 300, weightUnit: 'мл' },
            ],
          },
        ],
        modifierGroups: [
          additivesGroup,
          {
            id: 'syrup',
            label: 'Сироп',
            multi: false,
            required: false,
            modifiers: [
              { id: 'syrup-none', label: 'Без сиропа', calories: 0, protein: 0, fat: 0, carbs: 0, weight: 0, weightUnit: 'мл' },
              { id: 'syrup-15', label: 'Сироп 15 мл', calories: 45, protein: 0, fat: 0, carbs: 11, weight: 15, weightUnit: 'мл' },
              { id: 'syrup-20', label: 'Сироп 20 мл', calories: 60, protein: 0, fat: 0, carbs: 15, weight: 20, weightUnit: 'мл' },
              { id: 'syrup-25', label: 'Сироп 25 мл', calories: 75, protein: 0, fat: 0, carbs: 19, weight: 25, weightUnit: 'мл' },
            ],
          },
          {
            id: 'milk-add',
            label: 'Молоко +50 мл',
            multi: false,
            required: false,
            modifiers: [
              { id: 'milk-add-no', label: 'Без молока', calories: 0, protein: 0, fat: 0, carbs: 0, weight: 0, weightUnit: 'мл' },
              { id: 'milk-add-classic', label: 'Классическое', calories: 30, protein: 1.5, fat: 1.8, carbs: 2.4, weight: 50, weightUnit: 'мл' },
              { id: 'milk-add-coconut', label: 'Кокосовое Planto', calories: 16, protein: 0.5, fat: 0.7, carbs: 1.9, weight: 50, weightUnit: 'мл' },
              { id: 'milk-add-banana', label: 'Банановое Planto', calories: 22, protein: 0.6, fat: 0.4, carbs: 4.2, weight: 50, weightUnit: 'мл' },
              { id: 'milk-add-almond', label: 'Миндальное Planto', calories: 12, protein: 0.2, fat: 0.6, carbs: 1.5, weight: 50, weightUnit: 'мл' },
              { id: 'milk-add-hazelnut', label: 'Фундучное Гринмилк', calories: 23, protein: 0.5, fat: 1, carbs: 2.8, weight: 50, weightUnit: 'мл' },
              { id: 'milk-add-lactose', label: 'Безлактозное Parmalat', calories: 24, protein: 1.5, fat: 0.9, carbs: 2.4, weight: 50, weightUnit: 'мл' },
            ],
          },
        ],
      },
      {
        id: 'flat-white',
        name: 'Флэт уайт',
        description: 'Двойной эспрессо с молоком',
        weight: 160, weightUnit: 'мл',
        calories: 97, protein: 4.7, fat: 5.1, carbs: 7.6,
        categoryId: 'drinks-classic', venueId: '1', isAvailable: true,
        modifierGroups: [milkModifierGroup, additivesGroup],
      },
      {
        id: 'cappuccino',
        name: 'Капучино',
        description: 'Эспрессо, молочная пена',
        weight: 250, weightUnit: 'мл',
        calories: 108, protein: 5.2, fat: 5.8, carbs: 8.5,
        categoryId: 'drinks-classic', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'volume',
            label: 'Объём',
            required: true,
            options: [
              { id: 'v-025', label: '0.25', calories: 108, protein: 5.2, fat: 5.8, carbs: 8.5, weight: 250, weightUnit: 'мл' },
              { id: 'v-03', label: '0.3', calories: 168, protein: 8.2, fat: 9.0, carbs: 13.3, weight: 300, weightUnit: 'мл' },
            ],
          },
        ],
        modifierGroups: [milkModifierGroup, additivesGroup],
      },
      {
        id: 'latte',
        name: 'Латте',
        description: 'Эспрессо, молоко',
        weight: 300, weightUnit: 'мл',
        calories: 173, protein: 8.4, fat: 9.3, carbs: 13.6,
        categoryId: 'drinks-classic', venueId: '1', isAvailable: true,
        modifierGroups: [milkModifierGroup, additivesGroup],
      },
      {
        id: 'mocco',
        name: 'Мокко',
        description: 'Эспрессо, шоколад, молоко',
        weight: 300, weightUnit: 'мл',
        calories: 228, protein: 8.3, fat: 12.9, carbs: 19.0,
        categoryId: 'drinks-classic', venueId: '1', isAvailable: true,
        modifierGroups: [milkModifierGroup, additivesGroup],
      },
      {
        id: 'raf',
        name: 'Раф',
        description: 'Эспрессо, сливки, ваниль',
        weight: 300, weightUnit: 'мл',
        calories: 315, protein: 8.8, fat: 19.8, carbs: 24.8,
        categoryId: 'drinks-classic', venueId: '1', isAvailable: true,
        modifierGroups: [additivesGroup],
      },
      {
        id: 'matcha-latte',
        name: 'Матча-латте',
        description: 'Японский матча, молоко',
        weight: 250, weightUnit: 'мл',
        calories: 112, protein: 5.8, fat: 6.0, carbs: 8.6,
        categoryId: 'drinks-classic', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'volume',
            label: 'Объём',
            required: true,
            options: [
              { id: 'v-025', label: '0.25', calories: 112, protein: 5.8, fat: 6.0, carbs: 8.6, weight: 250, weightUnit: 'мл' },
              { id: 'v-03', label: '0.3', calories: 167, protein: 8.8, fat: 8.9, carbs: 12.9, weight: 300, weightUnit: 'мл' },
            ],
          },
        ],
        modifierGroups: [milkModifierGroup, additivesGroup],
      },
      {
        id: 'cocoa',
        name: 'Какао',
        description: 'Натуральное какао',
        weight: 200, weightUnit: 'мл',
        calories: 137, protein: 7.1, fat: 7.2, carbs: 11.1,
        categoryId: 'drinks-classic', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'volume',
            label: 'Объём',
            required: true,
            options: [
              { id: 'v-02', label: '0.2', calories: 137, protein: 7.1, fat: 7.2, carbs: 11.1, weight: 200, weightUnit: 'мл' },
              { id: 'v-03', label: '0.3', calories: 205, protein: 10.7, fat: 10.7, carbs: 16.5, weight: 300, weightUnit: 'мл' },
            ],
          },
        ],
        modifierGroups: [milkModifierGroup, additivesGroup],
      },
      {
        id: 'orange-fresh',
        name: 'Апельсиновый фреш',
        description: 'Свежевыжатый апельсин',
        weight: 200, weightUnit: 'мл',
        calories: 90, protein: 2.3, fat: 0.5, carbs: 20.3,
        categoryId: 'drinks-classic', venueId: '1', isAvailable: true,
      },
    ],
  },
  {
    id: 'drinks-author',
    name: 'Авторские напитки',
    venueId: '1',
    order: 2,
    items: [
      {
        id: 'peanut-raf',
        name: 'Арахисовый раф',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 352, protein: 13.4, fat: 20.5, carbs: 28.2,
        categoryId: 'drinks-author', venueId: '1', isAvailable: true,
        modifierGroups: [milkModifierGroup],
      },
      {
        id: 'latte-mint',
        name: 'Латте мята-лайм-гибискус',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 199, protein: 8, fat: 4, carbs: 23.2,
        categoryId: 'drinks-author', venueId: '1', isAvailable: true,
        modifierGroups: [milkModifierGroup],
      },
      {
        id: 'latte-pear',
        name: 'Латте груша-карамель',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 165, protein: 4.5, fat: 4.8, carbs: 26.9,
        categoryId: 'drinks-author', venueId: '1', isAvailable: true,
        modifierGroups: [milkModifierGroup],
      },
      {
        id: 'latte-raspberry',
        name: 'Латте малина-фиалка',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 256, protein: 7.8, fat: 8.3, carbs: 38.8,
        categoryId: 'drinks-author', venueId: '1', isAvailable: true,
        modifierGroups: [milkModifierGroup],
      },
      {
        id: 'plum-glintv',
        name: 'Сливовый глинтвейн',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 91, protein: 0.3, fat: 0, carbs: 22,
        categoryId: 'drinks-author', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'volume',
            label: 'Объём',
            required: true,
            options: [
              { id: 'v-03', label: '0.3', calories: 91, protein: 0.3, fat: 0, carbs: 22, weight: 300, weightUnit: 'мл' },
              { id: 'v-04', label: '0.4', calories: 114, protein: 0.4, fat: 0, carbs: 27.8, weight: 400, weightUnit: 'мл' },
            ],
          },
        ],
      },
      {
        id: 'mango-shake',
        name: 'Манговый милкшейк',
        description: '',
        weight: 400, weightUnit: 'мл',
        calories: 469, protein: 10.8, fat: 20.4, carbs: 61.4,
        categoryId: 'drinks-author', venueId: '1', isAvailable: true,
      },
      {
        id: 'smoothie-pine',
        name: 'Смузи ананас-мята',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 258, protein: 2.8, fat: 0.3, carbs: 64.2,
        categoryId: 'drinks-author', venueId: '1', isAvailable: true,
      },
      {
        id: 'smoothie-spinach',
        name: 'Смузи шпинат-финик',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 241, protein: 4.5, fat: 0.5, carbs: 59.7,
        categoryId: 'drinks-author', venueId: '1', isAvailable: true,
      },
      {
        id: 'smoothie-protein',
        name: 'Протеиновый смузи лесные ягоды',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 391, protein: 26.8, fat: 6, carbs: 13,
        categoryId: 'drinks-author', venueId: '1', isAvailable: true,
      },
    ],
  },
  {
    id: 'drinks-tea',
    name: 'Чай и холодные',
    venueId: '1',
    order: 3,
    items: [
      {
        id: 'tea-sea',
        name: 'Облепиховый чай',
        description: '',
        weight: 500, weightUnit: 'мл',
        calories: 174, protein: 1.5, fat: 4.3, carbs: 31.8,
        categoryId: 'drinks-tea', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'format',
            label: 'Формат',
            required: true,
            options: [
              { id: 'teapot', label: 'Чайник', calories: 174, protein: 1.5, fat: 4.3, carbs: 31.8, weight: 500, weightUnit: 'мл' },
              { id: 'togo', label: 'To go', calories: 127, protein: 1, fat: 3.2, carbs: 23.4, weight: 350, weightUnit: 'мл' },
            ],
          },
        ],
      },
      {
        id: 'tea-lemon',
        name: 'Лимонно-имбирный чай',
        description: '',
        weight: 500, weightUnit: 'мл',
        calories: 190, protein: 0.7, fat: 0, carbs: 43.7,
        categoryId: 'drinks-tea', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'format',
            label: 'Формат',
            required: true,
            options: [
              { id: 'teapot', label: 'Чайник', calories: 190, protein: 0.7, fat: 0, carbs: 43.7, weight: 500, weightUnit: 'мл' },
              { id: 'togo', label: 'To go', calories: 157, protein: 0.4, fat: 0, carbs: 36.7, weight: 350, weightUnit: 'мл' },
            ],
          },
        ],
      },
      {
        id: 'tea-rose',
        name: 'Роза-клубника',
        description: '',
        weight: 500, weightUnit: 'мл',
        calories: 234, protein: 0.9, fat: 0.2, carbs: 56.4,
        categoryId: 'drinks-tea', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'format',
            label: 'Формат',
            required: true,
            options: [
              { id: 'teapot', label: 'Чайник', calories: 234, protein: 0.9, fat: 0.2, carbs: 56.4, weight: 500, weightUnit: 'мл' },
              { id: 'togo', label: 'To go', calories: 162, protein: 0.5, fat: 0.1, carbs: 39.1, weight: 350, weightUnit: 'мл' },
            ],
          },
        ],
      },
      {
        id: 'tea-cherry',
        name: 'Вишня-бергамот',
        description: '',
        weight: 500, weightUnit: 'мл',
        calories: 173, protein: 0.8, fat: 0.2, carbs: 40.3,
        categoryId: 'drinks-tea', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'format',
            label: 'Формат',
            required: true,
            options: [
              { id: 'teapot', label: 'Чайник', calories: 173, protein: 0.8, fat: 0.2, carbs: 40.3, weight: 500, weightUnit: 'мл' },
              { id: 'togo', label: 'To go', calories: 135, protein: 0.6, fat: 0.2, carbs: 32.2, weight: 350, weightUnit: 'мл' },
            ],
          },
        ],
      },
      {
        id: 'ice-latte',
        name: 'Айс-латте с сиропом',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 196, protein: 7.2, fat: 7.7, carbs: 24.3,
        categoryId: 'drinks-tea', venueId: '1', isAvailable: true,
        modifierGroups: [milkModifierGroup],
      },
      {
        id: 'espresso-tonic',
        name: 'Эспрессо-тоник',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 43, protein: 0, fat: 0, carbs: 10.6,
        categoryId: 'drinks-tea', venueId: '1', isAvailable: true,
      },
      {
        id: 'bumble',
        name: 'Бамбл',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 153, protein: 0, fat: 0, carbs: 38.2,
        categoryId: 'drinks-tea', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'syrup',
            label: 'Сироп',
            required: true,
            options: [
              { id: 'with-syrup', label: 'С сиропом', calories: 153, protein: 0, fat: 0, carbs: 38.2, weight: 300, weightUnit: 'мл' },
              { id: 'no-syrup', label: 'Без сиропа', calories: 101, protein: 0, fat: 0, carbs: 25.2, weight: 300, weightUnit: 'мл' },
            ],
          },
        ],
      },
      {
        id: 'ice-matcha',
        name: 'Айс-матча латте',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 144, protein: 7.2, fat: 7.7, carbs: 11.3,
        categoryId: 'drinks-tea', venueId: '1', isAvailable: true,
        modifierGroups: [milkModifierGroup],
      },
      {
        id: 'ice-matcha-tonic',
        name: 'Айс-матча тоник',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 43, protein: 0, fat: 0, carbs: 10.6,
        categoryId: 'drinks-tea', venueId: '1', isAvailable: true,
      },
      {
        id: 'ice-rooibos',
        name: 'Айс ти сливочный ройбуш',
        description: '',
        weight: 300, weightUnit: 'мл',
        calories: 196, protein: 7.2, fat: 7.7, carbs: 24.3,
        categoryId: 'drinks-tea', venueId: '1', isAvailable: true,
      },
    ],
  },

  // ─── ЕДА ───────────────────────────────────────────────────
  {
    id: 'food-tortilla',
    name: 'Тортилья',
    venueId: '1',
    order: 4,
    items: [
      {
        id: 'tortilla',
        name: 'Тортилья',
        description: 'Пшеничная лепёшка с начинкой на выбор',
        weight: 300, weightUnit: 'г',
        calories: 326, protein: 10, fat: 16, carbs: 37,
        categoryId: 'food-tortilla', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'filling',
            label: 'Начинка',
            required: true,
            options: [
              { id: 'veg', label: 'С овощами', calories: 326, protein: 10, fat: 16, carbs: 37, weight: 300, weightUnit: 'г' },
              { id: 'chicken', label: 'С курицей', calories: 357, protein: 18, fat: 16, carbs: 35, weight: 300, weightUnit: 'г' },
              { id: 'salmon', label: 'С лососем', calories: 391, protein: 16, fat: 20, carbs: 37, weight: 300, weightUnit: 'г' },
              { id: 'shrimp', label: 'С креветкой', calories: 335, protein: 18, fat: 12, carbs: 38, weight: 300, weightUnit: 'г' },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'food-bowl',
    name: 'Боул',
    venueId: '1',
    order: 5,
    items: [
      {
        id: 'bowl',
        name: 'Боул',
        description: 'Питательный боул с крупой и начинкой на выбор',
        weight: 400, weightUnit: 'г',
        calories: 220, protein: 8, fat: 9.5, carbs: 23,
        categoryId: 'food-bowl', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'filling',
            label: 'Начинка',
            required: true,
            options: [
              { id: 'veg', label: 'Вегетарианский', calories: 0, protein: 0, fat: 0, carbs: 0, weight: 0, weightUnit: 'г' },
              { id: 'chicken', label: 'С курицей', calories: 0, protein: 0, fat: 0, carbs: 0, weight: 0, weightUnit: 'г' },
              { id: 'salmon', label: 'С лососем', calories: 0, protein: 0, fat: 0, carbs: 0, weight: 0, weightUnit: 'г' },
              { id: 'shrimp', label: 'С креветкой', calories: 0, protein: 0, fat: 0, carbs: 0, weight: 0, weightUnit: 'г' },
              { id: 'tuna', label: 'С тунцом', calories: 0, protein: 0, fat: 0, carbs: 0, weight: 0, weightUnit: 'г' },
            ],
          },
          {
            id: 'grain',
            label: 'Крупа',
            required: true,
            options: [
              { id: 'bulgur', label: 'Булгур', calories: 0, protein: 0, fat: 0, carbs: 0, weight: 0, weightUnit: 'г' },
              { id: 'quinoa', label: 'Киноа', calories: 0, protein: 0, fat: 0, carbs: 0, weight: 0, weightUnit: 'г' },
              { id: 'buckwheat', label: 'Гречка', calories: 0, protein: 0, fat: 0, carbs: 0, weight: 0, weightUnit: 'г' },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'food-main',
    name: 'Основные блюда',
    venueId: '1',
    order: 6,
    items: [
      { id: 'pasta', name: 'Паста карбонара', description: '', weight: 350, weightUnit: 'г', calories: 760, protein: 47.9, fat: 30.6, carbs: 70.4, categoryId: 'food-main', venueId: '1', isAvailable: true },
      { id: 'burger-doctor', name: 'Бургер с докторской и омлетом', description: '', weight: 350, weightUnit: 'г', calories: 646, protein: 23.6, fat: 45.9, carbs: 35.4, categoryId: 'food-main', venueId: '1', isAvailable: true },
      { id: 'burger-shrimp', name: 'Бургер с креветкой и авокадо', description: '', weight: 320, weightUnit: 'г', calories: 525, protein: 19.3, fat: 32.7, carbs: 40.2, categoryId: 'food-main', venueId: '1', isAvailable: true },
      { id: 'shakshuka', name: 'Шакшука', description: '', weight: 300, weightUnit: 'г', calories: 306, protein: 18.6, fat: 24.3, carbs: 31, categoryId: 'food-main', venueId: '1', isAvailable: true },
      { id: 'buckwheat-turkey', name: 'Греча с индейкой и яйцом пашот', description: '', weight: 400, weightUnit: 'г', calories: 581, protein: 46, fat: 24.7, carbs: 49, categoryId: 'food-main', venueId: '1', isAvailable: true },
    ],
  },
  {
    id: 'food-breakfast',
    name: 'Завтраки',
    venueId: '1',
    order: 7,
    items: [
      { id: 'avocado-toast', name: 'Авокадо тост', description: '', weight: 250, weightUnit: 'г', calories: 466, protein: 18.8, fat: 33.2, carbs: 24.3, categoryId: 'food-breakfast', venueId: '1', isAvailable: true },
      {
        id: 'croissant',
        name: 'Круассан',
        description: '',
        weight: 200, weightUnit: 'г',
        calories: 479, protein: 13, fat: 29, carbs: 44,
        categoryId: 'food-breakfast', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'filling',
            label: 'Начинка',
            required: true,
            options: [
              { id: 'salmon', label: 'С лососем', calories: 479, protein: 13, fat: 29, carbs: 44, weight: 200, weightUnit: 'г' },
              { id: 'brie', label: 'С бри и вишней', calories: 457, protein: 13, fat: 28, carbs: 37, weight: 200, weightUnit: 'г' },
            ],
          },
        ],
      },
      {
        id: 'brioche',
        name: 'Бриошь',
        description: '',
        weight: 150, weightUnit: 'г',
        calories: 345, protein: 9.7, fat: 26.7, carbs: 17.4,
        categoryId: 'food-breakfast', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'filling',
            label: 'Начинка',
            required: true,
            options: [
              { id: 'butter-caviar', label: 'С маслом и икрой', calories: 345, protein: 9.7, fat: 26.7, carbs: 17.4, weight: 150, weightUnit: 'г' },
              { id: 'berries', label: 'С ягодами', calories: 642, protein: 12, fat: 30, carbs: 84, weight: 200, weightUnit: 'г' },
            ],
          },
        ],
      },
      {
        id: 'waffle',
        name: 'Вафля сырная',
        description: '',
        weight: 300, weightUnit: 'г',
        calories: 652, protein: 32, fat: 37, carbs: 48,
        categoryId: 'food-breakfast', venueId: '1', isAvailable: true,
        variantGroups: [
          {
            id: 'filling',
            label: 'Начинка',
            required: true,
            options: [
              { id: 'salmon', label: 'С лососем', calories: 652, protein: 32, fat: 37, carbs: 48, weight: 300, weightUnit: 'г' },
              { id: 'avocado', label: 'С авокадо и икрой', calories: 466, protein: 22.6, fat: 32.6, carbs: 21.4, weight: 280, weightUnit: 'г' },
              { id: 'plain', label: 'Без начинки', calories: 187, protein: 7.5, fat: 9.9, carbs: 16.9, weight: 100, weightUnit: 'г' },
            ],
          },
        ],
      },
      { id: 'syrnik', name: 'Сырник со сметаной, черникой и маком', description: '', weight: 300, weightUnit: 'г', calories: 616, protein: 24.1, fat: 38.5, carbs: 40.4, categoryId: 'food-breakfast', venueId: '1', isAvailable: true },
    ],
  },
  {
    id: 'food-kids',
    name: 'Детское меню',
    venueId: '1',
    order: 8,
    items: [
      { id: 'kids-turkey', name: 'Индейка с овощами', description: '', weight: 250, weightUnit: 'г', calories: 183, protein: 33, fat: 3, carbs: 18.7, categoryId: 'food-kids', venueId: '1', isAvailable: true },
      { id: 'kids-soup', name: 'Суп с фрикадельками', description: '', weight: 300, weightUnit: 'г', calories: 176, protein: 10.9, fat: 5.7, carbs: 20.6, categoryId: 'food-kids', venueId: '1', isAvailable: true },
      { id: 'kids-patty', name: 'Биточки из индейки с пюре', description: '', weight: 300, weightUnit: 'г', calories: 593, protein: 25, fat: 41, carbs: 29.7, categoryId: 'food-kids', venueId: '1', isAvailable: true },
      { id: 'kids-pasta', name: 'Макарошки с сыром', description: '', weight: 250, weightUnit: 'г', calories: 328, protein: 14, fat: 18.9, carbs: 24.8, categoryId: 'food-kids', venueId: '1', isAvailable: true },
    ],
  },
  {
    id: 'sweets',
    name: 'Десерты',
    venueId: '1',
    order: 9,
    items: [
      { id: 'tart-flower', name: 'Тарт цветок', description: '', weight: 120, weightUnit: 'г', calories: 496, protein: 6.2, fat: 32.7, carbs: 44.8, categoryId: 'sweets', venueId: '1', isAvailable: true },
      { id: 'tiramisu', name: 'Тирамису', description: '', weight: 130, weightUnit: 'г', calories: 345, protein: 7.3, fat: 26, carbs: 19.3, categoryId: 'sweets', venueId: '1', isAvailable: true },
      { id: 'cheesecake', name: 'Чизкейк', description: '', weight: 130, weightUnit: 'г', calories: 522, protein: 8.8, fat: 38.6, carbs: 34.5, categoryId: 'sweets', venueId: '1', isAvailable: true },
      { id: 'medovik', name: 'Медовик', description: '', weight: 120, weightUnit: 'г', calories: 387, protein: 6.4, fat: 11.3, carbs: 64.7, categoryId: 'sweets', venueId: '1', isAvailable: true },
      { id: 'brownie', name: 'Брауни картошка', description: '', weight: 80, weightUnit: 'г', calories: 208, protein: 2.3, fat: 14.2, carbs: 18, categoryId: 'sweets', venueId: '1', isAvailable: true },
      { id: 'macaron-van', name: 'Макарун ванильный', description: '', weight: 30, weightUnit: 'г', calories: 328, protein: 6.6, fat: 15.9, carbs: 41.4, categoryId: 'sweets', venueId: '1', isAvailable: true },
      { id: 'macaron-choc', name: 'Макарун шоколадный', description: '', weight: 30, weightUnit: 'г', calories: 315, protein: 6.6, fat: 15.4, carbs: 39, categoryId: 'sweets', venueId: '1', isAvailable: true },
      { id: 'croissant-choc', name: 'Круассан шоколадный', description: 'Delifrance', weight: 80, weightUnit: 'г', calories: 246, protein: 5.4, fat: 2.7, carbs: 33.2, categoryId: 'sweets', venueId: '1', isAvailable: true },
      { id: 'eclair', name: 'Эклер', description: 'Ромбуле', weight: 80, weightUnit: 'г', calories: 278, protein: 4, fat: 14, carbs: 33, categoryId: 'sweets', venueId: '1', isAvailable: true },
    ],
  },
]

export const mockIngredients: IngredientRef[] = [
  // ─── МЯСО ───────────────────────────────────────────────────────────────
  { id: 'ing-lamb-1', name: 'Баранина 1 категория', unit: 'г', caloriesPer100: 209, proteinPer100: 15.6, fatPer100: 16.3, carbsPer100: 0, category: 'Мясо' },
  { id: 'ing-lamb-2', name: 'Баранина 2 категория', unit: 'г', caloriesPer100: 166, proteinPer100: 19.8, fatPer100: 9.6, carbsPer100: 0, category: 'Мясо' },
  { id: 'ing-beef-1', name: 'Говядина 1 категория', unit: 'г', caloriesPer100: 218, proteinPer100: 18.6, fatPer100: 16.0, carbsPer100: 0, category: 'Мясо' },
  { id: 'ing-beef-2', name: 'Говядина 2 категория', unit: 'г', caloriesPer100: 168, proteinPer100: 20.0, fatPer100: 9.8, carbsPer100: 0, category: 'Мясо' },
  { id: 'ing-horse-1', name: 'Конина 1 категория', unit: 'г', caloriesPer100: 167, proteinPer100: 19.5, fatPer100: 9.9, carbsPer100: 0, category: 'Мясо' },
  { id: 'ing-horse-2', name: 'Конина 2 категория', unit: 'г', caloriesPer100: 121, proteinPer100: 20.9, fatPer100: 4.1, carbsPer100: 0, category: 'Мясо' },
  { id: 'ing-rabbit', name: 'Кролик', unit: 'г', caloriesPer100: 183, proteinPer100: 21.2, fatPer100: 11.0, carbsPer100: 0, category: 'Мясо' },
  { id: 'ing-venison', name: 'Оленина', unit: 'г', caloriesPer100: 155, proteinPer100: 19.5, fatPer100: 8.5, carbsPer100: 0, category: 'Мясо' },
  { id: 'ing-pork-bacon', name: 'Свинина беконная', unit: 'г', caloriesPer100: 318, proteinPer100: 17.0, fatPer100: 27.8, carbsPer100: 0, category: 'Мясо' },
  { id: 'ing-pork-fat', name: 'Свинина жирная', unit: 'г', caloriesPer100: 491, proteinPer100: 11.7, fatPer100: 49.3, carbsPer100: 0, category: 'Мясо' },
  { id: 'ing-pork-meat', name: 'Свинина мясная', unit: 'г', caloriesPer100: 357, proteinPer100: 14.3, fatPer100: 33.3, carbsPer100: 0, category: 'Мясо' },
  { id: 'ing-veal-1', name: 'Телятина 1 категория', unit: 'г', caloriesPer100: 97, proteinPer100: 19.7, fatPer100: 2.0, carbsPer100: 0, category: 'Мясо' },
  { id: 'ing-veal-2', name: 'Телятина 2 категория', unit: 'г', caloriesPer100: 89, proteinPer100: 20.4, fatPer100: 0.9, carbsPer100: 0, category: 'Мясо' },

  // ─── ПТИЦА ───────────────────────────────────────────────────────────────
  { id: 'ing-broiler-1', name: 'Бройлеры 1 категория', unit: 'г', caloriesPer100: 220, proteinPer100: 18.7, fatPer100: 16.1, carbsPer100: 0, category: 'Птица' },
  { id: 'ing-broiler-2', name: 'Бройлеры 2 категория', unit: 'г', caloriesPer100: 180, proteinPer100: 19.7, fatPer100: 11.2, carbsPer100: 0, category: 'Птица' },
  { id: 'ing-goose-1', name: 'Гусь 1 категория', unit: 'г', caloriesPer100: 412, proteinPer100: 15.2, fatPer100: 39.0, carbsPer100: 0, category: 'Птица' },
  { id: 'ing-goose-2', name: 'Гусь 2 категория', unit: 'г', caloriesPer100: 317, proteinPer100: 17.0, fatPer100: 27.7, carbsPer100: 0, category: 'Птица' },
  { id: 'ing-turkey-1', name: 'Индейка 1 категория', unit: 'г', caloriesPer100: 276, proteinPer100: 19.5, fatPer100: 22.0, carbsPer100: 0, category: 'Птица' },
  { id: 'ing-turkey-2', name: 'Индейка 2 категория', unit: 'г', caloriesPer100: 194, proteinPer100: 21.6, fatPer100: 12.0, carbsPer100: 0, category: 'Птица' },
  { id: 'ing-chicken-1', name: 'Курица 1 категория', unit: 'г', caloriesPer100: 238, proteinPer100: 18.2, fatPer100: 18.4, carbsPer100: 0, category: 'Птица' },
  { id: 'ing-chicken-2', name: 'Курица 2 категория', unit: 'г', caloriesPer100: 159, proteinPer100: 21.2, fatPer100: 8.2, carbsPer100: 0, category: 'Птица' },
  { id: 'ing-duck-1', name: 'Утка 1 категория', unit: 'г', caloriesPer100: 405, proteinPer100: 15.8, fatPer100: 38.0, carbsPer100: 0, category: 'Птица' },
  { id: 'ing-duck-2', name: 'Утка 2 категория', unit: 'г', caloriesPer100: 287, proteinPer100: 17.2, fatPer100: 24.2, carbsPer100: 0, category: 'Птица' },

  // ─── РЫБА ────────────────────────────────────────────────────────────────
  { id: 'ing-pink-salmon', name: 'Горбуша', unit: 'г', caloriesPer100: 140, proteinPer100: 20.5, fatPer100: 6.5, carbsPer100: 0, category: 'Рыба' },
  { id: 'ing-cod', name: 'Треска', unit: 'г', caloriesPer100: 69, proteinPer100: 16.0, fatPer100: 0.6, carbsPer100: 0, category: 'Рыба' },
  { id: 'ing-pollock', name: 'Минтай', unit: 'г', caloriesPer100: 72, proteinPer100: 15.9, fatPer100: 0.9, carbsPer100: 0, category: 'Рыба' },
  { id: 'ing-mackerel', name: 'Скумбрия', unit: 'г', caloriesPer100: 191, proteinPer100: 18.0, fatPer100: 13.2, carbsPer100: 0, category: 'Рыба' },
  { id: 'ing-horse-mackerel', name: 'Ставрида', unit: 'г', caloriesPer100: 114, proteinPer100: 18.5, fatPer100: 4.5, carbsPer100: 0, category: 'Рыба' },
  { id: 'ing-sprat', name: 'Килька балтийская', unit: 'г', caloriesPer100: 137, proteinPer100: 14.1, fatPer100: 9.0, carbsPer100: 0, category: 'Рыба' },
  { id: 'ing-salmon', name: 'Лосось атлантический', unit: 'г', caloriesPer100: 153, proteinPer100: 20.0, fatPer100: 8.1, carbsPer100: 0, category: 'Рыба' },
  { id: 'ing-pike-perch', name: 'Судак', unit: 'г', caloriesPer100: 84, proteinPer100: 18.4, fatPer100: 1.1, carbsPer100: 0, category: 'Рыба' },
  { id: 'ing-pike', name: 'Щука', unit: 'г', caloriesPer100: 84, proteinPer100: 18.8, fatPer100: 1.1, carbsPer100: 0, category: 'Рыба' },
  { id: 'ing-carp', name: 'Карп', unit: 'г', caloriesPer100: 112, proteinPer100: 16.0, fatPer100: 5.3, carbsPer100: 0, category: 'Рыба' },
  { id: 'ing-herring', name: 'Сельдь атлантическая', unit: 'г', caloriesPer100: 161, proteinPer100: 17.7, fatPer100: 9.7, carbsPer100: 0, category: 'Рыба' },
  { id: 'ing-hake', name: 'Хек', unit: 'г', caloriesPer100: 86, proteinPer100: 16.6, fatPer100: 2.2, carbsPer100: 0, category: 'Рыба' },
  { id: 'ing-flounder', name: 'Камбала', unit: 'г', caloriesPer100: 83, proteinPer100: 15.7, fatPer100: 2.6, carbsPer100: 0, category: 'Рыба' },
  { id: 'ing-crucian', name: 'Карась', unit: 'г', caloriesPer100: 87, proteinPer100: 17.7, fatPer100: 1.8, carbsPer100: 0, category: 'Рыба' },
  { id: 'ing-perch', name: 'Окунь речной', unit: 'г', caloriesPer100: 82, proteinPer100: 18.5, fatPer100: 0.9, carbsPer100: 0, category: 'Рыба' },

  // ─── ЯЙЦА И МОЛОЧНОЕ ─────────────────────────────────────────────────────
  { id: 'ing-egg-chicken', name: 'Яйцо куриное', unit: 'г', caloriesPer100: 157, proteinPer100: 12.7, fatPer100: 11.5, carbsPer100: 0.7, category: 'Яйца и молочное' },
  { id: 'ing-milk-15', name: 'Молоко 1.5%', unit: 'мл', caloriesPer100: 45, proteinPer100: 3.0, fatPer100: 1.5, carbsPer100: 4.8, category: 'Яйца и молочное' },
  { id: 'ing-milk-25', name: 'Молоко 2.5%', unit: 'мл', caloriesPer100: 54, proteinPer100: 2.9, fatPer100: 2.5, carbsPer100: 4.8, category: 'Яйца и молочное' },
  { id: 'ing-milk-32', name: 'Молоко 3.2%', unit: 'мл', caloriesPer100: 60, proteinPer100: 2.9, fatPer100: 3.2, carbsPer100: 4.7, category: 'Яйца и молочное' },
  { id: 'ing-cream-10', name: 'Сливки 10%', unit: 'мл', caloriesPer100: 119, proteinPer100: 3.0, fatPer100: 10.0, carbsPer100: 4.0, category: 'Яйца и молочное' },
  { id: 'ing-cream-20', name: 'Сливки 20%', unit: 'мл', caloriesPer100: 207, proteinPer100: 2.8, fatPer100: 20.0, carbsPer100: 3.7, category: 'Яйца и молочное' },
  { id: 'ing-cream-35', name: 'Сливки 35%', unit: 'мл', caloriesPer100: 337, proteinPer100: 2.5, fatPer100: 35.0, carbsPer100: 3.2, category: 'Яйца и молочное' },
  { id: 'ing-cottage-fat', name: 'Творог 9% (полужирный)', unit: 'г', caloriesPer100: 159, proteinPer100: 16.7, fatPer100: 9.0, carbsPer100: 2.0, category: 'Яйца и молочное' },
  { id: 'ing-cottage-low', name: 'Творог нежирный', unit: 'г', caloriesPer100: 110, proteinPer100: 22.0, fatPer100: 0.6, carbsPer100: 3.3, category: 'Яйца и молочное' },
  { id: 'ing-sour-cream-15', name: 'Сметана 15%', unit: 'г', caloriesPer100: 158, proteinPer100: 2.6, fatPer100: 15.0, carbsPer100: 3.0, category: 'Яйца и молочное' },
  { id: 'ing-sour-cream-20', name: 'Сметана 20%', unit: 'г', caloriesPer100: 206, proteinPer100: 2.5, fatPer100: 20.0, carbsPer100: 3.2, category: 'Яйца и молочное' },
  { id: 'ing-kefir-15', name: 'Кефир 1.5%', unit: 'мл', caloriesPer100: 41, proteinPer100: 3.3, fatPer100: 1.5, carbsPer100: 4.1, category: 'Яйца и молочное' },
  { id: 'ing-kefir-32', name: 'Кефир 3.2%', unit: 'мл', caloriesPer100: 56, proteinPer100: 2.8, fatPer100: 3.2, carbsPer100: 4.1, category: 'Яйца и молочное' },

  // ─── МАСЛА И ЖИРЫ ────────────────────────────────────────────────────────
  { id: 'ing-butter', name: 'Масло сливочное', unit: 'г', caloriesPer100: 748, proteinPer100: 0.8, fatPer100: 82.5, carbsPer100: 0.8, category: 'Масла' },
  { id: 'ing-butter-ghee', name: 'Масло топлёное', unit: 'г', caloriesPer100: 892, proteinPer100: 0, fatPer100: 99.0, carbsPer100: 0, category: 'Масла' },
  { id: 'ing-sunflower-oil', name: 'Масло подсолнечное', unit: 'мл', caloriesPer100: 899, proteinPer100: 0, fatPer100: 99.9, carbsPer100: 0, category: 'Масла' },
  { id: 'ing-olive-oil', name: 'Масло оливковое', unit: 'мл', caloriesPer100: 898, proteinPer100: 0, fatPer100: 99.8, carbsPer100: 0, category: 'Масла' },
  { id: 'ing-corn-oil', name: 'Масло кукурузное', unit: 'мл', caloriesPer100: 899, proteinPer100: 0, fatPer100: 99.9, carbsPer100: 0, category: 'Масла' },
  { id: 'ing-linseed-oil', name: 'Масло льняное', unit: 'мл', caloriesPer100: 898, proteinPer100: 0, fatPer100: 99.8, carbsPer100: 0, category: 'Масла' },

  // ─── КРУПЫ И МУКА ────────────────────────────────────────────────────────
  { id: 'ing-buckwheat-raw', name: 'Гречневая крупа (ядрица)', unit: 'г', caloriesPer100: 329, proteinPer100: 12.6, fatPer100: 3.3, carbsPer100: 57.1, category: 'Крупы и мука' },
  { id: 'ing-oat', name: 'Крупа овсяная', unit: 'г', caloriesPer100: 345, proteinPer100: 12.0, fatPer100: 5.8, carbsPer100: 61.8, category: 'Крупы и мука' },
  { id: 'ing-rice', name: 'Крупа рисовая', unit: 'г', caloriesPer100: 330, proteinPer100: 7.0, fatPer100: 1.0, carbsPer100: 72.9, category: 'Крупы и мука' },
  { id: 'ing-millet', name: 'Крупа пшённая', unit: 'г', caloriesPer100: 334, proteinPer100: 11.5, fatPer100: 3.3, carbsPer100: 66.5, category: 'Крупы и мука' },
  { id: 'ing-semolina', name: 'Крупа манная', unit: 'г', caloriesPer100: 328, proteinPer100: 10.3, fatPer100: 1.0, carbsPer100: 70.6, category: 'Крупы и мука' },
  { id: 'ing-barley', name: 'Крупа ячневая', unit: 'г', caloriesPer100: 322, proteinPer100: 10.4, fatPer100: 1.3, carbsPer100: 66.3, category: 'Крупы и мука' },
  { id: 'ing-pearl-barley', name: 'Перловая крупа', unit: 'г', caloriesPer100: 324, proteinPer100: 9.3, fatPer100: 1.1, carbsPer100: 66.9, category: 'Крупы и мука' },
  { id: 'ing-corn-grits', name: 'Крупа кукурузная', unit: 'г', caloriesPer100: 337, proteinPer100: 8.3, fatPer100: 1.2, carbsPer100: 71.0, category: 'Крупы и мука' },
  { id: 'ing-wheat-flour', name: 'Мука пшеничная в/с', unit: 'г', caloriesPer100: 334, proteinPer100: 10.3, fatPer100: 1.1, carbsPer100: 68.9, category: 'Крупы и мука' },
  { id: 'ing-rye-flour', name: 'Мука ржаная', unit: 'г', caloriesPer100: 298, proteinPer100: 6.9, fatPer100: 1.1, carbsPer100: 61.8, category: 'Крупы и мука' },
  { id: 'ing-oatmeal', name: 'Толокно овсяное', unit: 'г', caloriesPer100: 357, proteinPer100: 12.5, fatPer100: 5.8, carbsPer100: 65.7, category: 'Крупы и мука' },

  // ─── БОБОВЫЕ ─────────────────────────────────────────────────────────────
  { id: 'ing-lentil', name: 'Чечевица', unit: 'г', caloriesPer100: 295, proteinPer100: 24.0, fatPer100: 1.5, carbsPer100: 46.3, category: 'Бобовые' },
  { id: 'ing-chickpea', name: 'Нут', unit: 'г', caloriesPer100: 309, proteinPer100: 19.0, fatPer100: 4.5, carbsPer100: 46.2, category: 'Бобовые' },
  { id: 'ing-peas', name: 'Горох', unit: 'г', caloriesPer100: 298, proteinPer100: 23.0, fatPer100: 1.6, carbsPer100: 46.5, category: 'Бобовые' },
  { id: 'ing-kidney-beans', name: 'Фасоль', unit: 'г', caloriesPer100: 292, proteinPer100: 22.3, fatPer100: 1.7, carbsPer100: 46.0, category: 'Бобовые' },
  { id: 'ing-soybean', name: 'Соя', unit: 'г', caloriesPer100: 364, proteinPer100: 34.9, fatPer100: 17.3, carbsPer100: 17.3, category: 'Бобовые' },

  // ─── ОВОЩИ ───────────────────────────────────────────────────────────────
  { id: 'ing-potato', name: 'Картофель', unit: 'г', caloriesPer100: 77, proteinPer100: 2.0, fatPer100: 0.1, carbsPer100: 16.3, category: 'Овощи' },
  { id: 'ing-carrot', name: 'Морковь', unit: 'г', caloriesPer100: 35, proteinPer100: 1.3, fatPer100: 0.1, carbsPer100: 6.9, category: 'Овощи' },
  { id: 'ing-beet', name: 'Свёкла', unit: 'г', caloriesPer100: 48, proteinPer100: 1.7, fatPer100: 0.1, carbsPer100: 9.6, category: 'Овощи' },
  { id: 'ing-cabbage-white', name: 'Капуста белокочанная', unit: 'г', caloriesPer100: 28, proteinPer100: 1.8, fatPer100: 0.1, carbsPer100: 4.7, category: 'Овощи' },
  { id: 'ing-onion', name: 'Лук репчатый', unit: 'г', caloriesPer100: 41, proteinPer100: 1.4, fatPer100: 0.2, carbsPer100: 8.2, category: 'Овощи' },
  { id: 'ing-tomato', name: 'Томаты', unit: 'г', caloriesPer100: 24, proteinPer100: 1.1, fatPer100: 0.2, carbsPer100: 3.8, category: 'Овощи' },
  { id: 'ing-cucumber', name: 'Огурцы', unit: 'г', caloriesPer100: 14, proteinPer100: 0.8, fatPer100: 0.1, carbsPer100: 2.1, category: 'Овощи' },
  { id: 'ing-bell-pepper', name: 'Перец сладкий', unit: 'г', caloriesPer100: 27, proteinPer100: 1.3, fatPer100: 0.1, carbsPer100: 5.7, category: 'Овощи' },
  { id: 'ing-eggplant', name: 'Баклажаны', unit: 'г', caloriesPer100: 24, proteinPer100: 1.2, fatPer100: 0.1, carbsPer100: 4.5, category: 'Овощи' },
  { id: 'ing-zucchini', name: 'Кабачки', unit: 'г', caloriesPer100: 24, proteinPer100: 0.6, fatPer100: 0.3, carbsPer100: 4.6, category: 'Овощи' },
  { id: 'ing-garlic', name: 'Чеснок', unit: 'г', caloriesPer100: 106, proteinPer100: 6.5, fatPer100: 0.5, carbsPer100: 21.2, category: 'Овощи' },
  { id: 'ing-spinach', name: 'Шпинат', unit: 'г', caloriesPer100: 23, proteinPer100: 2.9, fatPer100: 0.3, carbsPer100: 2.3, category: 'Овощи' },
  { id: 'ing-green-peas', name: 'Горошек зелёный свежий', unit: 'г', caloriesPer100: 73, proteinPer100: 5.0, fatPer100: 0.2, carbsPer100: 13.3, category: 'Овощи' },
  { id: 'ing-pumpkin', name: 'Тыква', unit: 'г', caloriesPer100: 28, proteinPer100: 1.3, fatPer100: 0.3, carbsPer100: 4.9, category: 'Овощи' },
  { id: 'ing-leek', name: 'Лук-порей', unit: 'г', caloriesPer100: 40, proteinPer100: 2.0, fatPer100: 0.2, carbsPer100: 7.3, category: 'Овощи' },
  { id: 'ing-celery-root', name: 'Сельдерей (корень)', unit: 'г', caloriesPer100: 32, proteinPer100: 1.3, fatPer100: 0.3, carbsPer100: 6.5, category: 'Овощи' },
  { id: 'ing-parsnip', name: 'Пастернак', unit: 'г', caloriesPer100: 74, proteinPer100: 1.4, fatPer100: 0.5, carbsPer100: 15.6, category: 'Овощи' },
  { id: 'ing-radish', name: 'Редис', unit: 'г', caloriesPer100: 21, proteinPer100: 1.2, fatPer100: 0.1, carbsPer100: 3.4, category: 'Овощи' },
  { id: 'ing-broccoli', name: 'Брокколи', unit: 'г', caloriesPer100: 28, proteinPer100: 3.0, fatPer100: 0.4, carbsPer100: 2.2, category: 'Овощи' },
  { id: 'ing-cauliflower', name: 'Капуста цветная', unit: 'г', caloriesPer100: 30, proteinPer100: 2.5, fatPer100: 0.3, carbsPer100: 4.2, category: 'Овощи' },

  // ─── ФРУКТЫ И ЯГОДЫ ──────────────────────────────────────────────────────
  { id: 'ing-apple', name: 'Яблоки', unit: 'г', caloriesPer100: 46, proteinPer100: 0.4, fatPer100: 0.4, carbsPer100: 9.8, category: 'Фрукты' },
  { id: 'ing-pear', name: 'Груши', unit: 'г', caloriesPer100: 47, proteinPer100: 0.4, fatPer100: 0.3, carbsPer100: 10.3, category: 'Фрукты' },
  { id: 'ing-orange', name: 'Апельсины', unit: 'г', caloriesPer100: 43, proteinPer100: 0.9, fatPer100: 0.2, carbsPer100: 8.4, category: 'Фрукты' },
  { id: 'ing-tangerine', name: 'Мандарины', unit: 'г', caloriesPer100: 40, proteinPer100: 0.8, fatPer100: 0.3, carbsPer100: 7.5, category: 'Фрукты' },
  { id: 'ing-banana', name: 'Бананы', unit: 'г', caloriesPer100: 91, proteinPer100: 1.5, fatPer100: 0.2, carbsPer100: 21.8, category: 'Фрукты' },
  { id: 'ing-grape', name: 'Виноград', unit: 'г', caloriesPer100: 65, proteinPer100: 0.6, fatPer100: 0.2, carbsPer100: 15.0, category: 'Фрукты' },
  { id: 'ing-peach', name: 'Персики', unit: 'г', caloriesPer100: 44, proteinPer100: 0.9, fatPer100: 0.1, carbsPer100: 9.5, category: 'Фрукты' },
  { id: 'ing-plum', name: 'Слива', unit: 'г', caloriesPer100: 49, proteinPer100: 0.8, fatPer100: 0.3, carbsPer100: 9.9, category: 'Фрукты' },
  { id: 'ing-cherry', name: 'Черешня', unit: 'г', caloriesPer100: 52, proteinPer100: 1.1, fatPer100: 0.4, carbsPer100: 10.6, category: 'Фрукты' },
  { id: 'ing-sour-cherry', name: 'Вишня', unit: 'г', caloriesPer100: 52, proteinPer100: 0.8, fatPer100: 0.5, carbsPer100: 10.6, category: 'Фрукты' },
  { id: 'ing-strawberry', name: 'Клубника', unit: 'г', caloriesPer100: 41, proteinPer100: 1.8, fatPer100: 0.4, carbsPer100: 6.3, category: 'Фрукты' },
  { id: 'ing-blueberry', name: 'Черника', unit: 'г', caloriesPer100: 44, proteinPer100: 1.1, fatPer100: 0.6, carbsPer100: 6.6, category: 'Фрукты' },
  { id: 'ing-raspberry', name: 'Малина', unit: 'г', caloriesPer100: 46, proteinPer100: 0.8, fatPer100: 0.5, carbsPer100: 8.3, category: 'Фрукты' },
  { id: 'ing-currant-black', name: 'Смородина чёрная', unit: 'г', caloriesPer100: 44, proteinPer100: 1.0, fatPer100: 0.2, carbsPer100: 7.3, category: 'Фрукты' },
  { id: 'ing-watermelon', name: 'Арбуз', unit: 'г', caloriesPer100: 38, proteinPer100: 0.7, fatPer100: 0.2, carbsPer100: 7.9, category: 'Фрукты' },
  { id: 'ing-melon', name: 'Дыня', unit: 'г', caloriesPer100: 35, proteinPer100: 0.6, fatPer100: 0.3, carbsPer100: 7.4, category: 'Фрукты' },
  { id: 'ing-lemon', name: 'Лимон', unit: 'г', caloriesPer100: 34, proteinPer100: 0.9, fatPer100: 0.1, carbsPer100: 3.6, category: 'Фрукты' },
  { id: 'ing-apricot', name: 'Абрикосы', unit: 'г', caloriesPer100: 44, proteinPer100: 0.9, fatPer100: 0.1, carbsPer100: 9.0, category: 'Фрукты' },
]

/**
 * Системные библиотеки от сервиса NutriMenu.
 * Подключаются через initLibraries() и доступны только для чтения владельцем.
 */
export const systemLibraries: IngredientLibrary[] = [
  {
    id: 'system-base',
    name: 'Базовые продукты HoReCa',
    isSystem: true,
    ingredients: systemIngredients,
  },
  foodDatabaseLibrary,
]